name: Changelog CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          changelog_filename: CHANGELOG.md
          committer_username: 'test'
          committer_email: 'test@test.com'
          release_version: '0.0.16'
          github_token: ${{ secrets.github_token }}
